<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProjectSOA/Project1/createAuto" name="createAuto-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProjectSOA/Project1/createAuto" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProjectSOA/Project1/createAuto" location="../WSDL/createAuto.wsdl"/>
  <binding name="createAuto_ptt-binding" type="tns:createAuto_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="createAuto">
      <soap:operation soapAction="createAuto"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="createAuto-service">
    <port name="createAuto-port" binding="tns:createAuto_ptt-binding">
      <soap:address location="jca://eis/DB/Connection1"/>
    </port>
  </service>
</definitions>