<?binding.jca createAuto_db.jca?>
<wsdl:definitions name="createAuto" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProjectSOA/Project1/createAuto" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/createAuto" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProjectSOA/Project1/createAuto" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="createAuto_plt">
        <plt:role name="createAuto_role">
            <plt:portType name="tns:createAuto_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/createAuto" schemaLocation="xsd/createAuto_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="createAuto_ptt">
        <wsdl:operation name="createAuto">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
